name: MonkeyType Readme
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: ridemountainpig/monkeytype-readme@master
        with:
          username: anshul_01
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
